### ISSUE TITLE
Add an RST linter in a github action for README.rst and HISTORY.rst

### ISSUE THREAD

**Issue by jpichon** [release-depot/git_wrapper#75]
We use a combination of README.rst and HISTORY.rst in the long_description for setup.cfg. That means a parsing error will make the upload to Pypi fail (see for example https://github.com/release-depot/git_wrapper/pull/74).

Adding a github action to check those files ahead of merging would help to prevent this.

**Comment by jpichon** [comment]
This is the command I used locally to check these files, though we might not actually need the output part in an automated check?

    $ python -m readme_renderer README.rst -o /tmp/README.html
    $ python -m readme_renderer HISTORY.rst -o /tmp/HISTORY.html

(cf README instructions at https://github.com/release-depot/git_wrapper#pushing-a-new-release)

**Comment by jguiditta** [comment]
This is just a thought, but I took a look at readme-renderer, and they mention you can run 'twine check' to validate the rst[1].  Would this simplify anything or allow us to not need the extra dep for the renderer?
[1] https://packaging.python.org/guides/making-a-pypi-friendly-readme/#validating-restructuredtext-markup

**Comment by jpichon** [comment]
Gave it a shot and it does seem to pick up the issue as expected, nice!

Current master:
```
$ twine check dist/*
Checking dist/git_wrapper-0.2.8.dev1-py3-none-any.whl: PASSED, with warnings
  warning: `long_description_content_type` missing. defaulting to `text/x-rst`.
Checking dist/git_wrapper-0.2.8.dev1.tar.gz: PASSED, with warnings
  warning: `long_description_content_type` missing. defaulting to `text/x-rst`.
$ echo $?
0
```

After reproducing the old indendation error:

```
$ twine check dist/*
Checking dist/git_wrapper-0.2.8.dev1-py3-none-any.whl: FAILED
  `long_description` has syntax errors in markup and would not be rendered on PyPI.
    line 172: Warning: Block quote ends without a blank line; unexpected unindent.
  warning: `long_description_content_type` missing. defaulting to `text/x-rst`.
Checking dist/git_wrapper-0.2.8.dev1.tar.gz: FAILED
  `long_description` has syntax errors in markup and would not be rendered on PyPI.
    line 172: Warning: Block quote ends without a blank line; unexpected unindent.
  warning: `long_description_content_type` missing. defaulting to `text/x-rst`.
$ echo $?
1
```

So I agree that we should update the README, as it's much simpler to use the same tool for both checking and uploading.

I think there would still be value in adding a github action so we catch these early rather than last minute like we are now (and creating a new patch to fix the typo last minute, etc). Either way, leaving this open as this would make a good initial task for an intern.

**Comment by jpichon** [comment]
This is where the git_wrapper CI jobs are defined: https://github.com/release-depot/git_wrapper/blob/master/.github/workflows/test.yml (currently 3 job definitions for test, flake8 and integration jobs).

**Comment by kyleecodes** [comment]
> That is great, having a 0/1 lets us hook it to CI nice and easily! Maybe it could go in the syntax check job, so we verify on each commit? Maybe we could do something even more conditional, like check only if the rst files were changed, istr something like that in the github actions docs, but I am not positive.

What does "istr" stand for in this context?

**Comment by jpichon** [comment]
Probably something like "I seem to remember", I think. I wouldn't worry about the conditional check to start with, just running the twine check would work fine as a first iteration.

**Comment by jpichon** [comment]
PR merged.
